-- OBJECTIVE QUESTIONS

-- Q1: What is the total number of attributes in the customer table?

-- method 1 , visual check
describe customers;

-- Method 2, using information_schema
SELECT COUNT(*) 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ecommerce_project'
AND TABLE_NAME = 'customers';

-- Q2: How will you get the “Customer’s” ages in the “Order” tables according to customer IDs?

select o.*, c.CustomerAge
from orders o
join customers c on o.CustomerID=c.CustomerID;

-- Q3: In analyzing the dataset with Power BI, ensure data cleaning to address inconsistencies and missing values before further analysis.

-- Q4: How can we calculate the total revenue generated by all the sales?
select sum(SalePrice) as total_revenue
from orders;

-- Q5: What is the total number of unique customers who made purchases each year? Is there any increase in the number over the years?
  
select year(OrderDate) as Purchase_year, count(distinct CustomerID) as unique_customers,
count(distinct CustomerID)-lag(count(distinct CustomerID)) over(order by year(OrderDate) asc) as Difference,
round((count(distinct CustomerID)-lag(count(distinct CustomerID)) over(order by year(OrderDate) asc))*100.0/lag(count(distinct CustomerID)) over(order by year(OrderDate) asc),2) as YoY_growth_percentage

from orders
group by year(OrderDate);

-- Q6: How can we determine the total number of unique products available in the company?
select count(distinct Product) as Unique_products from orders;

-- Q7: What is the average number of days it takes for products to be delivered, get the metric for only the delivered orders. 
select avg(Datediff(DeliveryDate,OrderDate)) as avg_days
from orders 
where Status='Delivered';

-- Q8: Which products, categories, and subcategories are the most popular? 
with cte as(
select Product, sum(OrderQuantity) as Qty_ordered, rank() over(order by sum(OrderQuantity) desc) as rnk
from orders
group by Product
)
select *
from cte 
where rnk=1;

-- Similarly for categories and Subcategories
with cte as(
select ProductCategory, sum(OrderQuantity) as Qty_ordered, rank() over(order by sum(OrderQuantity) desc) as rnk
from orders
group by ProductCategory
)
select *
from cte 
where rnk=1;

with cte as(
select SubCategory, sum(OrderQuantity) as Qty_ordered, rank() over(order by sum(OrderQuantity) desc) as rnk
from orders
group by SubCategory
)
select *
from cte 
where rnk=1;

-- Q9: Which products have seen an increase or decrease in sales over the years? 
with cte as(
select Product, year(OrderDate) as order_year, sum(SalePrice) as revenue
from orders
group by Product, year(OrderDate)
),
cte2 as(
select *,
revenue- lag(revenue) over(partition by Product order by order_year asc) as YoY_difference,
case
when revenue- lag(revenue) over(partition by Product order by order_year asc) <0 then 'Decrease'
when revenue- lag(revenue) over(partition by Product order by order_year asc) =0 then 'Same'
when revenue- lag(revenue) over(partition by Product order by order_year asc) >0 then 'Increase'
else null
end as YoY_Trend,
row_number() over(partition by Product order by order_year asc) as rn

from cte
order by Product, order_year asc)

select *,
case 
when (select revenue from cte2 where Product=c.Product and rn= (select max(rn) from cte2 where Product=c.Product)) < (select revenue from cte2 where Product=c.Product and rn=1) then 'Net Decrease'
when (select revenue from cte2 where Product=c.Product and rn= (select max(rn) from cte2 where Product=c.Product)) = (select revenue from cte2 where Product=c.Product and rn=1) then 'Net Neutral'
when (select revenue from cte2 where Product=c.Product and rn= (select max(rn) from cte2 where Product=c.Product)) > (select revenue from cte2 where Product=c.Product and rn=1) then 'Net Increase'
end as Net_Change
from cte2 c;


-- Q14: Identify the top 5 most valuable customers using a composite score that combines three key metrics: (SQL)
-- Total Revenue (50% weight): The total amount of money spent by the customer.
-- Order Frequency (30% weight): The number of orders placed by the customer, indicating their loyalty and engagement.
-- Average Order Value (20% weight): The average value of each order placed by the customer, reflecting the typical transaction size.

with customer_metrics as(
select CustomerID, round(sum(SalePrice),2) as total_revenue, count(distinct OrderID) as frequency, round(avg(SalePrice),2) as avg_order_value
from orders
where Status= 'Delivered'
group by CustomerID
),
normalized as(
    SELECT *,
        PERCENT_RANK() OVER (ORDER BY total_revenue) AS revenue_score,
        PERCENT_RANK() OVER (ORDER BY frequency) AS frequency_score,
        PERCENT_RANK() OVER (ORDER BY avg_order_value) AS aov_score
    FROM customer_metrics
    )
SELECT 
    CustomerID,
    total_revenue,
    frequency,
    avg_order_value,
    ROUND(
        0.5 * revenue_score +
        0.3 * frequency_score +
        0.2 * aov_score
    , 4) AS composite_score
FROM normalized
ORDER BY composite_score DESC
LIMIT 5;


-- Q15: Calculate the month-over-month growth rate in total revenue across the entire dataset. (SQL)
with cte as(
select DATE_FORMAT(OrderDate, '%Y-%m') as Year_Month_period, sum(SalePrice) as Total_Revenue
from orders o
group by DATE_FORMAT(OrderDate, '%Y-%m')
)
select * , 
round(((Total_Revenue-lag(Total_Revenue) over(order by Year_Month_period))*100.0/lag(Total_Revenue) over(order by Year_Month_period)),2) as MoM_Growth_rate
from cte ;

-- Q16: Calculate the rolling 3-month average revenue for each product category. (SQL)
with cte as(
select ProductCategory, date_format(OrderDate,'%Y-%m') as Year_month_period, sum(SalePrice) as Revenue
from orders
where Status= 'Delivered'
group by ProductCategory, date_format(OrderDate,'%Y-%m')
)

select *, 
round(avg(Revenue) over(partition by ProductCategory order by Year_month_period rows between 2 preceding and current row),2) as three_month_rolling_avg
from cte;

-- Q17: Update the orders table to apply a 15% discount on the `Sale Price` for orders placed by customers who have made at least 10 orders. (SQL)

-- Not using Update delibrately, because we dont want to change the actual data for the sake of this question
SELECT *,
CASE 
WHEN CustomerID IN (SELECT CustomerID FROM orders GROUP BY CustomerID HAVING COUNT(DISTINCT OrderID) >= 10) THEN ROUND(SalePrice * 0.85, 2)
ELSE 'No discount'
END AS discounted_price
FROM orders;

-- Q18: Calculate the average number of days between consecutive orders for customers who have placed at least five orders. (SQL)
select CustomerID
from orders 
group by CustomerID
having count(*)>=5;

-- just to double check: 
SELECT CustomerID, COUNT(DISTINCT OrderID) AS order_count
FROM orders
GROUP BY CustomerID
ORDER BY order_count DESC
LIMIT 10;

-- Q19: Identify customers who have generated revenue that is more than 30% higher than the average revenue per customer. (SQL)
with total as(
select CustomerID, sum(SalePrice) as total_rev_from_customer
from orders
group by CustomerID
),
average as(
select avg(total_rev_from_customer) as avg_rev_per_customer
from total
)
select CustomerID
from total
where total_rev_from_customer> 1.3*(select avg_rev_per_customer from average);


-- Q20: Determine the top 3 product categories that have shown the highest increase in sales over the past year compared to the previous year. (SQL)
with cte as(
select ProductCategory,
sum(case when year(OrderDate)=2019 then SalePrice end) as Rev_2019,
sum(case when year(OrderDate)=2020 then SalePrice end) as Rev_2020
from orders
where Status='Delivered'
group by ProductCategory
)

select *, Rev_2020-Rev_2019 as Change_in_Rev
from cte
order by Change_in_Rev desc
limit 3;